# Generated by Django 3.2.5 on 2021-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='fully_vaccinated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='own_house',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='survey',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
